## BÀI 1: LÀM QUEN VỚI PYTORCH

#### Bài 1. Tạo Tensor cơ bản

In [1]:
import torch

a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Bài 2. Tạo các Tensor thường dùng

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[5.5190e-01, 6.7419e-01, 1.2353e-01, 1.9762e-01],
        [6.9755e-04, 6.0044e-01, 9.8628e-01, 2.4813e-01],
        [7.1188e-01, 4.4346e-01, 5.1408e-01, 1.9606e-01]])
tensor([[ 1.0814, -0.6011,  0.4681, -0.4726],
        [ 0.6023,  0.0285, -0.5150, -0.3184],
        [ 1.8977,  0.0842,  2.1152, -0.4712]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#### Bài 3. Kiểm tra thông tin Tensor

In [3]:
import torch
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


#### Bài 4. Slicing và Indexing

In [4]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.0338, -0.7326, -0.4063, -0.6557,  0.1623],
         [-0.0569, -0.3589, -1.0597, -0.3620, -0.8814],
         [-0.2310,  0.4117, -0.9474,  0.0732, -0.0298],
         [-2.1900, -0.0428,  1.8385,  1.0193, -0.1929]],

        [[-0.4768, -1.0554, -1.4867, -0.9839,  0.1118],
         [-1.2861, -1.7360,  0.5198, -0.2628,  1.0126],
         [-0.6317,  0.5051, -0.2996, -0.3623, -1.5531],
         [-0.0983, -0.8751, -0.3466,  0.0900, -0.4922]],

        [[ 2.8120, -0.7072, -0.0158,  0.5243,  1.1778],
         [-0.3852, -0.7289,  0.6417,  0.1528, -0.9658],
         [ 0.1085, -0.1297,  0.8208,  0.4197, -0.3196],
         [ 0.7853,  0.2968, -0.2820, -0.9797, -0.6680]]])

Tensor a[1]:
tensor([[-0.4768, -1.0554, -1.4867, -0.9839,  0.1118],
        [-1.2861, -1.7360,  0.5198, -0.2628,  1.0126],
        [-0.6317,  0.5051, -0.2996, -0.3623, -1.5531],
        [-0.0983, -0.8751, -0.3466,  0.0900, -0.4922]])

Tensor a[1:, 2:4]:
tensor([[[-0.6317,  0.5051, -0.2996, -0.3623, -1.5

#### Bài 5. Reshape và Flatten

In [5]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.7570,  0.9513, -0.7320, -0.6657],
        [ 0.2157,  0.5370, -1.8423, -0.6936],
        [-0.8682, -2.1683, -0.9072, -0.3238]])

Flatten:
tensor([ 0.7570,  0.9513, -0.7320, -0.6657,  0.2157,  0.5370, -1.8423, -0.6936,
        -0.8682, -2.1683, -0.9072, -0.3238])

Reshape to 3 x 2 x 2:
tensor([[[ 0.7570,  0.9513],
         [-0.7320, -0.6657]],

        [[ 0.2157,  0.5370],
         [-1.8423, -0.6936]],

        [[-0.8682, -2.1683],
         [-0.9072, -0.3238]]])


#### Bài 6. Phép toán và nhân ma trận

In [6]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.6728,  0.8003,  1.0409],
        [-0.8840,  1.3069,  0.4219]])
b:
tensor([[1.0368, 0.5282, 0.3450],
        [0.5115, 0.0110, 0.2851]])

a + b:
tensor([[ 1.7096,  1.3285,  1.3859],
        [-0.3726,  1.3179,  0.7071]])

a / b:
tensor([[  0.6490,   1.5150,   3.0171],
        [ -1.7285, 119.1630,   1.4796]])

a^2:
tensor([[0.4527, 0.6404, 1.0834],
        [0.7815, 1.7080, 0.1780]])

Matrix multiplication:
tensor([[ 1.4794,  0.6497],
        [-0.0807, -0.3175]])


#### Bài 7. Các hàm thống kê trên Tensor

In [19]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.1916,  0.5644, -2.1752, -0.4078],
        [-0.2609, -1.2903,  1.3285,  1.5328],
        [ 1.2911, -0.0125, -1.4349,  1.8639]])

Mean:
tensor([ 0.4073, -0.2461, -0.7605,  0.9963])

Standard deviation:
tensor([0.7982, 0.9492, 1.8466, 1.2272])

Cumulative sum:
tensor([[ 0.1916,  0.5644, -2.1752, -0.4078],
        [-0.0694, -0.7259, -0.8467,  1.1250],
        [ 1.2218, -0.7383, -2.2816,  2.9889]])


#### Bài 8. Autograd cơ bản

In [8]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


#### Bài 9. Gradient Descent tìm hệ số đa thức

In [10]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
 optimizer.zero_grad()
y_pred = x @ w
mse = torch.mean(torch.square(y - y_pred))
mse.backward()
optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 0.9169],
        [-0.3609],
        [-0.2531]], requires_grad=True)
Learned coefficients:
tensor([[ 0.9274],
        [-0.3503],
        [-0.2425]], requires_grad=True)


#### Bài 10. Giải hệ phương trình bằng Autograd

In [ ]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
 y1 = A + B - 9
 y2 = C - D - 1
 y3 = A + C - 8
 y4 = B - D - 2
sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
optimizer.zero_grad()
sqerr.backward()
optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(0.7244, requires_grad=True)
B = tensor(0.3087, requires_grad=True)
C = tensor(0.8080, requires_grad=True)
D = tensor(0.6023, requires_grad=True)


#### Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:

##### a) Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.

In [13]:
import torch

# Tạo Tensor X gồm 24 phần tử
X = torch.arange(1, 25)

print("Tensor X:")
print(X)

# Reshape thành 4 x 6
X_4x6 = X.reshape(4, 6)
print("\nX có kích thước 4 x 6:")
print(X_4x6)

# Reshape thành 2 x 12
X_2x12 = X.reshape(2, 12)
print("\nX có kích thước 2 x 12:")
print(X_2x12)

# Reshape thành 2 x 3 x 4
X_2x3x4 = X.reshape(2, 3, 4)
print("\nX có kích thước 2 x 3 x 4:")
print(X_2x3x4)

Tensor X:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

X có kích thước 4 x 6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

X có kích thước 2 x 12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

X có kích thước 2 x 3 x 4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


##### b) Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.

In [ ]:
import torch

# Tạo Tensor A và B kích thước 3 x 4
A = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
], dtype=torch.float32)

B = torch.tensor([
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]
], dtype=torch.float32)

print("A + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình theo cột:")
print(A.mean(dim=0))

print("\nĐộ lệch chuẩn theo cột:")
print(A.std(dim=0))

A + B:
tensor([[ 3.,  4.,  5.,  6.],
        [ 8.,  9., 10., 11.],
        [13., 14., 15., 16.]])

A * B:
tensor([[ 2.,  4.,  6.,  8.],
        [15., 18., 21., 24.],
        [36., 40., 44., 48.]])

A / B:
tensor([[0.5000, 1.0000, 1.5000, 2.0000],
        [1.6667, 2.0000, 2.3333, 2.6667],
        [2.2500, 2.5000, 2.7500, 3.0000]])

Trung bình theo cột:
tensor([5., 6., 7., 8.])

Độ lệch chuẩn theo cột:
tensor([4., 4., 4., 4.])


##### c) Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

In [15]:
import torch

# Tạo x = 2 và cho phép PyTorch tính đạo hàm
x = torch.tensor(2.0, requires_grad=True)

# Hàm y
y = 2 * x**2 + 5 * x + 3

# Tính đạo hàm dy/dx
y.backward()

print("x =", x.item())
print("y =", y.item())
print("dy/dx =", x.grad.item())

x = 2.0
y = 21.0
dy/dx = 13.0


##### d) Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [ ]:
import torch

x = torch.linspace(-5, 5, 100)
y = 2 * x**2 - 3 * x + 5

a = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
c = torch.tensor(0.0, requires_grad=True)

learning_rate = 0.001

for epoch in range(5000):

    y_pred = a * x**2 + b * x + c

    loss = torch.mean((y_pred - y)**2)

    loss.backward()

    with torch.no_grad():
        a -= learning_rate * a.grad
        b -= learning_rate * b.grad
        c -= learning_rate * c.grad

    a.grad.zero_()
    b.grad.zero_()
    c.grad.zero_()

print("Hệ số a =", a.item())
print("Hệ số b =", b.item())
print("Hệ số c =", c.item())

Hệ số a = 2.003800868988037
Hệ số b = -2.999993324279785
Hệ số c = 4.942046165466309
